version: 2

registries:
  github-maven-navikt:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt
    username: x-access-token
    password: ${{secrets.GITHUB_TOKEN}}

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - github-maven-navikt
    schedule:
      interval: weekly
      day: tuesday
      time: "03:00"
      timezone: Europe/Oslo
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10