---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-pdfgen
  namespace: amt
  labels:
    team: amt
spec:
  port: 8080
  prometheus:
    enabled: true
    path: "/internal/prometheus"
  startup:
    path: "/internal/is_alive"
    initialDelay: 20
    failureThreshold: 20
  readiness:
    path: "/internal/is_alive"
  liveness:
    path: "/internal/is_alive"
  replicas:
    disableAutoScaling: true
  resources:
    requests:
      cpu: 10m
  accessPolicy:
    inbound:
      rules:
        - application: amt-distribusjon
