spring.main.banner-mode=off
server.shutdown=graceful
spring.threads.virtual.enabled=true
spring.lifecycle.timeout-per-shutdown-phase=25s

management.endpoint.prometheus.access=read_only
management.endpoint.health.probes.enabled=true
management.endpoint.health.group.liveness.include=livenessState
management.endpoints.web.base-path=/internal
management.endpoints.web.exposure.include=prometheus,health
management.prometheus.metrics.export.enabled=true

nais.env.azureAppClientId=${AZURE_APP_CLIENT_ID}
nais.env.azureAppJWK=${AZURE_APP_JWK}
nais.env.azureOpenIdConfigTokenEndpoint=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}

spring.datasource.url=${DB_JDBC_URL}
spring.datasource.hikari.maximum-pool-size=3

kafka.auto-offset-reset=earliest

no.nav.security.jwt.client.registration.amt-arena-acl.token-endpoint-url=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
no.nav.security.jwt.client.registration.amt-arena-acl.grant-type=client_credentials
no.nav.security.jwt.client.registration.amt-arena-acl.scope=${AMT_ARENA_ACL_SCOPE}
no.nav.security.jwt.client.registration.amt-arena-acl.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.amt-arena-acl.authentication.client-jwk=${AZURE_APP_JWK}
no.nav.security.jwt.client.registration.amt-arena-acl.authentication.client-auth-method=private_key_jwt

no.nav.security.jwt.client.registration.amt-arrangor.token-endpoint-url=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
no.nav.security.jwt.client.registration.amt-arrangor.grant-type=client_credentials
no.nav.security.jwt.client.registration.amt-arrangor.scope=${AMT_ARRANGOR_SCOPE}
no.nav.security.jwt.client.registration.amt-arrangor.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.amt-arrangor.authentication.client-jwk=${AZURE_APP_JWK}
no.nav.security.jwt.client.registration.amt-arrangor.authentication.client-auth-method=private_key_jwt

no.nav.security.jwt.client.registration.aktivitet-arena-acl.token-endpoint-url=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
no.nav.security.jwt.client.registration.aktivitet-arena-acl.grant-type=client_credentials
no.nav.security.jwt.client.registration.aktivitet-arena-acl.scope=${AKTIVITET_ARENA_ACL_SCOPE}
no.nav.security.jwt.client.registration.aktivitet-arena-acl.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.aktivitet-arena-acl.authentication.client-jwk=${AZURE_APP_JWK}
no.nav.security.jwt.client.registration.aktivitet-arena-acl.authentication.client-auth-method=private_key_jwt

no.nav.security.jwt.client.registration.veilarboppfolging.token-endpoint-url=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
no.nav.security.jwt.client.registration.veilarboppfolging.grant-type=client_credentials
no.nav.security.jwt.client.registration.veilarboppfolging.scope=${VEILARBOPPFOLGING_SCOPE}
no.nav.security.jwt.client.registration.veilarboppfolging.authentication.client-id=${AZURE_APP_CLIENT_ID}
no.nav.security.jwt.client.registration.veilarboppfolging.authentication.client-jwk=${AZURE_APP_JWK}
no.nav.security.jwt.client.registration.veilarboppfolging.authentication.client-auth-method=private_key_jwt

amt.arena-acl.url=${AMT_ARENA_ACL_URL}
amt.arrangor.url=${AMT_ARRANGOR_URL}
aktivitet.arena-acl.url=${AKTIVITET_ARENA_ACL_URL}
veilarboppfolging.url=${VEILARBOPPFOLGING_URL}

app.env.unleashUrl=${UNLEASH_SERVER_API_URL}/api
app.env.unleashApiToken=${UNLEASH_SERVER_API_TOKEN}

veilederurl.basepath=${VEILEDERURL_BASEPATH}
deltakerurl.basepath=${DELTAKERURL_BASEPATH}
