spring.main.banner-mode=off
server.shutdown=graceful
spring.threads.virtual.enabled=true
spring.lifecycle.timeout-per-shutdown-phase=25s

spring.http.clients.connect-timeout=5s
spring.http.clients.read-timeout=10s

management.endpoint.prometheus.access=read_only
management.endpoint.health.probes.enabled=true
management.endpoint.health.group.liveness.include=livenessState
management.endpoints.web.base-path=/internal
management.endpoints.web.exposure.include=prometheus,health
management.prometheus.metrics.export.enabled=true

spring.datasource.url=${DB_JDBC_URL}
spring.datasource.hikari.maximum-pool-size=3

kafka.auto-offset-reset=earliest

spring.security.oauth2.client.provider.azuread.token-uri=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}

spring.http.serviceclient.amt-arena-acl.base-url=${AMT_ARENA_ACL_URL}
spring.http.serviceclient.amt-arrangor.base-url=${AMT_ARRANGOR_URL}
spring.http.serviceclient.aktivitet-arena-acl.base-url=${AKTIVITET_ARENA_ACL_URL}
spring.http.serviceclient.veilarboppfolging.base-url=${VEILARBOPPFOLGING_URL}

spring.security.oauth2.client.registration.amt-arena-acl.provider=azuread
spring.security.oauth2.client.registration.amt-arena-acl.client-id=${AZURE_APP_CLIENT_ID}
spring.security.oauth2.client.registration.amt-arena-acl.client-secret=${AZURE_APP_CLIENT_SECRET}
spring.security.oauth2.client.registration.amt-arena-acl.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.amt-arena-acl.scope=${AMT_ARENA_ACL_SCOPE}

spring.security.oauth2.client.registration.amt-arrangor.provider=azuread
spring.security.oauth2.client.registration.amt-arrangor.client-id=${AZURE_APP_CLIENT_ID}
spring.security.oauth2.client.registration.amt-arrangor.client-secret=${AZURE_APP_CLIENT_SECRET}
spring.security.oauth2.client.registration.amt-arrangor.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.amt-arrangor.scope=${AMT_ARRANGOR_SCOPE}

spring.security.oauth2.client.registration.aktivitet-arena-acl.provider=azuread
spring.security.oauth2.client.registration.aktivitet-arena-acl.client-id=${AZURE_APP_CLIENT_ID}
spring.security.oauth2.client.registration.aktivitet-arena-acl.client-secret=${AZURE_APP_CLIENT_SECRET}
spring.security.oauth2.client.registration.aktivitet-arena-acl.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.aktivitet-arena-acl.scope=${AKTIVITET_ARENA_ACL_SCOPE}

spring.security.oauth2.client.registration.veilarboppfolging.provider=azuread
spring.security.oauth2.client.registration.veilarboppfolging.client-id=${AZURE_APP_CLIENT_ID}
spring.security.oauth2.client.registration.veilarboppfolging.client-secret=${AZURE_APP_CLIENT_SECRET}
spring.security.oauth2.client.registration.veilarboppfolging.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.veilarboppfolging.scope=${VEILARBOPPFOLGING_SCOPE}

app.env.unleashUrl=${UNLEASH_SERVER_API_URL}/api
app.env.unleashApiToken=${UNLEASH_SERVER_API_TOKEN}

veilederurl.basepath=${VEILEDERURL_BASEPATH}
deltakerurl.basepath=${DELTAKERURL_BASEPATH}
