DB_JDBC_URL=jdbc:postgresql://localhost:5432/amt_tiltaksarrangor_bff_db
logging.config=classpath:logback-local.xml
spring.datasource.username=myuser
spring.datasource.password=mypassword
server.port=8088
elector.path=dont_look_for_leader
KAFKA_BROKERS=localhost:9092
KAFKA_SECURITY_PROTOCOL=PLAINTEXT
KAFKA_TRUSTSTORE_PATH=
KAFKA_CREDSTORE_PASSWORD=
KAFKA_KEYSTORE_PATH=
UNLEASH_SERVER_API_URL=http://localhost:9002/unleash
UNLEASH_SERVER_API_TOKEN=dummy
TOKEN_X_WELL_KNOWN_URL=http://localhost:9000/azure/.well-known/openid-configuration
TOKEN_X_TOKEN_ENDPOINT=http://localhost:9000/azure/token
TOKEN_X_CLIENT_ID=amt-tiltaksarrangor-bff-client-id
TOKEN_X_PRIVATE_JWK={"kty":"RSA","kid":"local","e":"AQAB","n":"test"}
AZURE_APP_WELL_KNOWN_URL=http://localhost:9000/azure/.well-known/openid-configuration
AZURE_OPENID_CONFIG_TOKEN_ENDPOINT=http://localhost:9000/azure/token
AZURE_APP_CLIENT_ID=amt-tiltaksarrangor-bff
AZURE_APP_CLIENT_SECRET=secret
#AMT_TILTAK_TOKENX_CLIENT_ID=dev-gcp:amt:amt-tiltak
#AMT_ARRANGOR_TOKENX_CLIENT_ID=dev-gcp:amt:amt-arrangor
#AMT_ARRANGOR_AAD_CLIENT_ID=api://dev-gcp.amt.amt-arrangor/.default
#AMT_PERSON_AAD_CLIENT_ID=api://dev-gcp.amt.amt-person-service/.default
#AMT_DELTAKER_AAD_CLIENT_ID=api://dev-gcp.amt.amt-deltaker/.default
amt-arrangor.url=http://localhost:8084
amt-person.url=http://localhost:8086

