kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-deltaker-bff
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - {{ingress}}
  prometheus:
    enabled: true
    path: /internal/prometheus

  startup:
    path: /internal/health/liveness
    initialDelay: 20
    failureThreshold: 20
  readiness:
    path: /internal/health/readiness
  liveness:
    path: /internal/health/liveness

  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
{{#if cpu_scaling_threshold}}
    scalingStrategy:
      cpu:
        thresholdPercentage: {{cpu_scaling_threshold}}
{{else}}
    disableAutoScaling: true
{{/if}}

  resources:
    requests:
      cpu: {{cpu_request}}
      memory: {{memory_request}}
    limits:
      memory: {{memory_limit}}
  envFrom:
    - secret: amt-deltaker-bff-unleash-api-token
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          - id: {{ad_rolle_tiltak_koordinator}}
    sidecar:
      enabled: true
  leaderElection: true
  kafka:
    pool: {{kafka_pool}}
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
{{#each inbound_rules}}
        - application: {{application}}
{{#if namespace}}
          namespace: {{namespace}}
{{/if}}
{{/each}}
    outbound:
      rules:
        - application: amt-arrangor
        - application: amt-person-service
        - application: amt-deltaker
        - application: amt-distribusjon
        - application: poao-tilgang
          namespace: poao
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
      external:
        - host: amt-unleash-api.nav.cloud.nais.io
  env:
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=80 -Xshare:off --enable-native-access=ALL-UNNAMED --sun-misc-unsafe-memory-access=allow"
    - name: AMT_ARRANGOR_SCOPE
      value: api://{{cluster}}.amt.amt-arrangor/.default
    - name: AMT_ARRANGOR_URL
      value: http://amt-arrangor
    - name: POAO_TILGANG_SCOPE
      value: api://{{cluster}}.poao.poao-tilgang/.default
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao
    - name: AMT_PERSONSERVICE_SCOPE
      value: api://{{cluster}}.amt.amt-person-service/.default
    - name: AMT_PERSONSERVICE_URL
      value: http://amt-person-service
    - name: AMT_DELTAKER_SCOPE
      value: api://{{cluster}}.amt.amt-deltaker/.default
    - name: AMT_DELTAKER_URL
      value: http://amt-deltaker
    - name: AMT_DISTRIBUSJON_SCOPE
      value: api://{{cluster}}.amt.amt-distribusjon/.default
    - name: AMT_DISTRIBUSJON_URL
      value: http://amt-distribusjon
    - name: AD_ROLLE_TILTAKSKOORDINATOR
      value: {{ad_rolle_tiltak_koordinator}}
    - name: MULIGHETSROMMET_API_SCOPE
      value: api://{{cluster}}.team-mulighetsrommet.mulighetsrommet-api/.default
    - name: MULIGHETSROMMET_API_URL
      value: http://mulighetsrommet-api.team-mulighetsrommet.svc.cluster.local

  gcp:
    sqlInstances:
      - name: {{database_instance}}
        tier: {{database_tier}}
        collation: nb_NO.UTF8
        type: POSTGRES_17
        databases:
          - name: amt-deltaker-bff
            envVarPrefix: DB
        diskAutoresize: {{database_disk_autoresize}}
        pointInTimeRecovery: {{database_point_in_time_recovery}}
        insights:
          enabled: {{database_insights}}

  observability:
      autoInstrumentation:
        enabled: true
        runtime: java
      logging:
        destinations:
          - id: elastic
          - id: loki
