---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-tiltaksarrangor-bff
  namespace: amt
  labels:
    team: amt
spec:
  port: 8080
  prometheus:
    enabled: true
    path: "/actuator/prometheus"
  startup:
    path: "/actuator/health/liveness"
    initialDelay: 20
    failureThreshold: 20
  readiness:
    path: "/actuator/health/readiness"
  liveness:
    path: "/actuator/health/liveness"
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltaksarrangor-flate
    outbound:
      rules:
        - application: amt-tiltak
        - application: amt-arrangor
        - application: amt-person-service
        - application: amt-deltaker
      external:
        - host: amt-unleash-api.nav.cloud.nais.io
  leaderElection: true
  envFrom:
    - secret: amt-tiltaksarrangor-bff-unleash-api-token
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
