name: amt-distribusjon - Run tests
on:
  push:
    paths:
      - "amt-distribusjon/**"
      - ".github/dependabot.yml"
    branches:
      - main

permissions:
  contents: "write"

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml
    with:
      module-path: "amt-distribusjon"