name: amt-tiltaksarrangor-bff - Deploy unleash-apitoken
on:
  push:
    paths:
      - "amt-tiltaksarrangor-bff/.nais/unleash-apitoken-dev.yaml"
      - "amt-tiltaksarrangor-bff/.nais/unleash-apitoken-prod.yaml"

permissions:
  id-token: write

jobs:
  call-deploy:
    uses: ./.github/workflows/reusable/deploy-unleash-apitoken.yml
    with:
      module-path: "amt-tiltaksarrangor-bff"