name: amt-lib - Create Release
on:
  workflow_dispatch: # This workflow can be triggered manually
  push:
    paths:
      - "amt-lib/**"
      - "gradle/libs.versions.toml"
      - "buildSrc/src/main/kotlin/amt-lib.conventions.gradle.kts"
    branches:
      - main

env:
  PRINT_PAYLOAD: true

jobs:
  test:
    name: Test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 25
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Run tests
        run: ./gradlew check -p amt-lib

  create-release:
    name: Create new release
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Create Version
        run: echo "VERSION=1.$(TZ=\"Europe/Oslo\" date +%Y.%m.%d_%H.%M)-$(git rev-parse --short=12 HEAD)" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 25
          cache: gradle

      - name: Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish -p amt-lib -Pversion="${{ env.VERSION }}" --no-configuration-cache

      - name: Create release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        with:
          name: Release ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          prerelease: false
