name: amt-felles - Run tests
on:
  push:
    paths:
      - "amt-felles/**"
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml
    with:
      module-path: "amt-felles"