name: amt-deltaker - Run tests
on:
  push:
    paths:
      - "amt-deltaker/**"
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml
    with:
      module-path: "amt-deltaker"