name: amt-deltaker - Run tests
on:
  push:
    paths:
      - "amt-deltaker/**"
      - "gradle/libs.versions.toml"
    branches-ignore:
      - main

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml
    with:
      module-path: "amt-deltaker"