name: amt-deltaker-bff - Deploy app
on:
  workflow_dispatch: # This workflow can be triggered manually
  push:
    paths:
      - "amt-deltaker-bff/**"
      - ".github/dependabot.yml"
    branches:
      - main

permissions:
  contents: write
  id-token: write
  security-events: write

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-app.yml
    with:
      module-path: "amt-deltaker-bff"