name: amt-deltaker-bff - Run tests
on:
  push:
    paths:
      - "amt-deltaker-bff/**"
      - ".github/dependabot.yml"
    branches-ignore:
      - main

permissions:
  contents: "write"

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml
    with:
      module-path: "amt-deltaker-bff"