name: amt-deltaker - Deploy app
on:
  workflow_dispatch: # This workflow can be triggered manually
  push:
    paths:
      - "amt-deltaker/**"
      - "gradle/libs.versions.toml"
    branches:
      - main

permissions:
  id-token: write

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-app.yml
    with:
      module-path: "amt-deltaker"