name: Deploy Unleash API Token

on:
  push:
    paths:
      - "*/.nais/unleash-apitoken-*.yaml"

permissions:
  contents: read
  id-token: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            amt-aktivitetskort-publisher:
              - amt-aktivitetskort-publisher/.nais/unleash-apitoken-*.yaml
            amt-deltaker-bff:
              - amt-deltaker-bff/.nais/unleash-apitoken-*.yaml
            amt-deltaker:
              - amt-deltaker/.nais/unleash-apitoken-*.yaml
            amt-tiltaksarrangor-bff:
              - amt-tiltaksarrangor-bff/.nais/unleash-apitoken-*.yaml

      - name: Debug changed modules
        run: |
          echo "Changed modules raw output:"
          echo '${{ steps.filter.outputs.changes }}'

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.modules != '[]' }}
    strategy:
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.modules) }}
    uses: ./.github/workflows/reusable-deploy-unleash-apitoken.yml
    with:
      module_path: ${{ matrix.module }}