name: Deploy Unleash API Token

on:
  push:
    paths:
      - "*/.nais/unleash-apitoken-*.yaml"

permissions:
  contents: read
  id-token: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            amt-deltaker-bff:
              - amt-deltaker-bff/.nais/unleash-apitoken-*.yaml
            amt-deltaker:
              - amt-deltaker/.nais/unleash-apitoken-*.yaml
            amt-tiltaksarrangor-bff:
              - amt-tiltaksarrangor-bff/.nais/unleash-apitoken-*.yaml

      - name: Debug changed modules
        run: |
          echo "Changed modules raw output:"
          echo '${{ steps.filter.outputs.changes }}'

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.modules != '[]' }}
    strategy:
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.modules) }}
    uses: ./.github/workflows/reusable-deploy-unleash-apitoken.yml
    with:
      module_path: ${{ matrix.module }}