name: Deploy amt-iac

on:
  push:
    branches:
      - main
    paths:
      - "amt-iac/**/*.yaml"
      - ".github/workflows/ci-deploy-iac.yml"

permissions:
  contents: read
  id-token: write

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      iac_folders: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            alerts/dev:
              - amt-iac/alerts/dev/**
            alerts/prod:
              - amt-iac/alerts/prod/**
            kafka-manager/dev:
              - amt-iac/kafka-manager/dev/**
            kafka-manager/prod:
              - amt-iac/kafka-manager/prod/**
            kafka-topic/dev:
              - amt-iac/kafka-topic/dev/**
            kafka-topic/prod:
              - amt-iac/kafka-topic/prod/**

      - name: Debug changed environments
        run: echo '${{ steps.filter.outputs.changes }}'

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.iac_folders != '[]' }}

    strategy:
      matrix:
        iac_folder: ${{ fromJSON(needs.changes.outputs.iac_folders) }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: List resource files
        run: echo "RESOURCE_FILES=$(find amt-iac/${{ matrix.iac_folder }} -type f -name '*.yaml' -printf '%p,' | sed 's/,$//')" >> $GITHUB_ENV

      - name: Deploy ${{ matrix.iac_folder }}
        if: ${{ endsWith(matrix.iac_folder, '/dev') }}
        uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ${{ env.RESOURCE_FILES }}
          PRINT_PAYLOAD: true

      - name: Deploy ${{ matrix.iac_folder }}
        if: ${{ github.ref == 'refs/heads/main' && endsWith(matrix.iac_folder, '/prod') }}
        uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: ${{ env.RESOURCE_FILES }}
          PRINT_PAYLOAD: true