name: Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - "amt-deltaker-bff/**"
      - "amt-deltaker/**"
      - "amt-distribusjon/**"
      - "amt-tiltaksarrangor-bff/**"

permissions:
  id-token: write

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            amt-deltaker-bff:
              - amt-deltaker-bff/**
              - gradle/libs.versions.toml

            amt-deltaker:
              - amt-deltaker/**
              - gradle/libs.versions.toml

            amt-distribusjon:
              - amt-distribusjon/**
              - gradle/libs.versions.toml

            amt-tiltaksarrangor-bff:
              - amt-tiltaksarrangor-bff/**
              - gradle/libs.versions.toml

      - name: Debug changed packages
        run: echo '${{ steps.filter.outputs.changes }}'

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}

    uses: ./.github/workflows/reusable-deploy-app.yml
    with:
      module-path: ${{ matrix.package }}