name: Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - "buildSrc/**"
      - "amt-aktivitetskort-publisher/**"
      - "amt-deltaker/**"
      - "amt-deltaker-bff/**"
      - "amt-distribusjon/**"
      - "amt-felles/**"
      - "amt-lib/**"
      - "amt-pdfgen/**"
      - "amt-tiltaksarrangor-bff/**"
      - "gradle/libs.versions.toml"

permissions:
  contents: write    # Required for dependency-graph submit in reusable workflow
  id-token: write    # Required for NAIS deploy/docker-build-push in reusable workflow

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      modules: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            amt-aktivitetskort-publisher:
              - amt-aktivitetskort-publisher/**
              - amt-felles/**
              - amt-lib/**
              - gradle/libs.versions.toml
              - buildSrc/**

            amt-deltaker-bff:
              - amt-deltaker-bff/**
              - amt-felles/**
              - amt-lib/**
              - gradle/libs.versions.toml
              - buildSrc/**

            amt-deltaker:
              - amt-deltaker/**
              - amt-felles/**
              - amt-lib/**
              - gradle/libs.versions.toml
              - buildSrc/**

            amt-distribusjon:
              - amt-distribusjon/**
              - amt-felles/**
              - amt-lib/**
              - gradle/libs.versions.toml
              - buildSrc/**

            amt-pdfgen:
              - amt-pdfgen/**
              - amt-felles/**
              - amt-lib/**
              - gradle/libs.versions.toml
              - buildSrc/**
    
            amt-tiltaksarrangor-bff:
              - amt-tiltaksarrangor-bff/**
              - amt-felles/**
              - amt-lib/**
              - gradle/libs.versions.toml
              - buildSrc/**

      - name: Debug changed modules
        run: echo '${{ steps.filter.outputs.changes }}'

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.modules != '[]' }}
    strategy:
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.modules) }}

    uses: ./.github/workflows/reusable-deploy-app.yml
    with:
      module_path: ${{ matrix.module }}
