name: Deploy amt-iac

on:
  push:
    branches:
      - main
    paths:
      - "amt-iac/**/*.yaml"
      - ".github/workflows/ci-deploy-iac.yml"

jobs:
  changes:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      iac_folders: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: filter
        with:
          filters: |
            alerts/dev:
              - amt-iac/alerts/dev/**
            alerts/prod:
              - amt-iac/alerts/prod/**
            kafka-manager/dev:
              - amt-iac/kafka-manager/dev/**
            kafka-manager/prod:
              - amt-iac/kafka-manager/prod/**
            kafka-topic/dev:
              - amt-iac/kafka-topic/dev/**
            kafka-topic/prod:
              - amt-iac/kafka-topic/prod/**

      - name: Debug changed environments
        run: echo '${{ steps.filter.outputs.changes }}'

  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.iac_folders != '[]' }}

    strategy:
      matrix:
        iac_folder: ${{ fromJSON(needs.changes.outputs.iac_folders) }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: List resource files
        run: echo "RESOURCE_FILES=$(find amt-iac/${{ matrix.iac_folder }} -type f -name '*.yaml' -printf '%p,' | sed 's/,$//')" >> $GITHUB_ENV

      - name: Deploy ${{ matrix.iac_folder }}
        if: ${{ endsWith(matrix.iac_folder, '/dev') }}
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ${{ env.RESOURCE_FILES }}
          PRINT_PAYLOAD: true

      - name: Deploy ${{ matrix.iac_folder }}
        if: ${{ github.ref == 'refs/heads/main' && endsWith(matrix.iac_folder, '/prod') }}
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: ${{ env.RESOURCE_FILES }}
          PRINT_PAYLOAD: true