name: Run tests

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      packages: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            amt-deltaker-bff: amt-deltaker-bff/**
            amt-deltaker: amt-deltaker/**
            amt-distribusjon: amt-distribusjon/**
            amt-felles: amt-felles/**
            amt-lib: amt-lib/**
            amt-tiltaksarrangor-bff: amt-tiltaksarrangor-bff/**
            all: gradle/libs.versions.toml

      - name: Debug changed packages
        run: |
          echo "Changed packages raw output:"
          echo '${{ steps.filter.outputs.changes }}'

  run-tests:
    needs: changes
    if: ${{ needs.changes.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      module-path: ${{ matrix.package }}