name: Run Tests

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      modules: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            amt-deltaker-bff: amt-deltaker-bff/**
            amt-deltaker: amt-deltaker/**
            amt-distribusjon: amt-distribusjon/**
            amt-felles: amt-felles/**
            amt-lib: amt-lib/**
            amt-pdfgen: amt-pdfgen/**
            amt-tiltaksarrangor-bff: amt-tiltaksarrangor-bff/**
            all: gradle/libs.versions.toml

      - name: Debug changed modules
        run: |
          echo "Changed modules raw output:"
          echo '${{ steps.filter.outputs.changes }}'

  run-tests:
    needs: changes
    if: ${{ needs.changes.outputs.modules != '[]' }}
    strategy:
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.modules) }}
    uses: ./.github/workflows/reusable-test.yml
    with:
      module_path: ${{ matrix.module }}