name: Reusable Deploy Unleash API Token

on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string

jobs:
  deploy-dev:
    name: Deploy ${{ inputs.module_path }} Unleash to dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@e90640a98702d2554350fb35c4d5d242dd8e4346 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ${{ inputs.module_path }}/.nais/unleash-apitoken-dev.yaml
          PRINT_PAYLOAD: true

  deploy-prod:
    name: Deploy ${{ inputs.module_path }} Unleash to prod
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@e90640a98702d2554350fb35c4d5d242dd8e4346 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: ${{ inputs.module_path }}/.nais/unleash-apitoken-prod.yaml