name: Reusable Deploy Application

on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string

env:
  PRINT_PAYLOAD: true

jobs:
  test-build-and-push:
    name: Test, build and push ${{ inputs.module_path }}
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Required for dependency-graph: generate-and-submit
      id-token: write    # Required for nais/docker-build-push OIDC
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'gradle'

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          dependency-graph: generate-and-submit

      - name: Build artifacts
        run: |
          GRADLE_ARGS="installDist"
          
          case "${{ inputs.module_path }}" in
            amt-tiltaksarrangor-bff|amt-pdfgen)
            GRADLE_ARGS=""
          ;;
          esac
          
          ./gradlew build \
            $GRADLE_ARGS \
            -p ${{ inputs.module_path }} \
            --no-daemon \
            --no-configuration-cache
# Kommenter inn ved behov
#            --info \
#            --console=plain \
#            --warning-mode=all

      - name: docker-build-push
        uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5 # v0
        id: docker-build-push
        with:
          team: amt
          image_suffix: ${{ inputs.module_path }}
          tag: ${{ github.sha }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          docker_context: ${{ inputs.module_path }}
          dockerfile: ${{ inputs.module_path }}/Dockerfile
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    name: Deploy ${{ inputs.module_path }} to dev
    needs: test-build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write    # Required for nais/deploy OIDC
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Deploy application
        uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ${{ inputs.module_path }}/.nais/nais-dev.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
          VARS: ${{ inputs.module_path }}/.nais/vars-dev.yaml

  deploy-prod:
    name: Deploy ${{ inputs.module_path }} to prod
    needs: [ test-build-and-push, deploy-dev ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write    # Required for nais/deploy OIDC
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Deploy application
        uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: ${{ inputs.module_path }}/.nais/nais-prod.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
          VARS: ${{ inputs.module_path }}/.nais/vars-prod.yaml