name: Reusable Deploy Application

on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string

env:
  PRINT_PAYLOAD: true

jobs:
  test-build-and-push:
    name: Test, build and push ${{ inputs.module_path }}
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Required for dependency-graph: generate-and-submit
      id-token: write    # Required for nais/docker-build-push OIDC
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Java
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          dependency-graph: generate-and-submit

      - name: Build artifacts
        run: |
          GRADLE_ARGS="installDist"
          
          case "${{ inputs.module_path }}" in
            amt-aktivitetskort-publisher|amt-tiltaksarrangor-bff|amt-pdfgen)
            GRADLE_ARGS=""
          ;;
          esac
          
          ./gradlew build \
            $GRADLE_ARGS \
            -p ${{ inputs.module_path }} \
            --no-daemon \
            --no-configuration-cache
# Kommenter inn ved behov
#            --info \
#            --console=plain \
#            --warning-mode=all

      - name: docker-build-push
        uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # v0
        id: docker-build-push
        with:
          team: amt
          image_suffix: ${{ inputs.module_path }}
          tag: ${{ github.sha }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          docker_context: ${{ inputs.module_path }}
          dockerfile: ${{ inputs.module_path }}/Dockerfile
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    name: Deploy ${{ inputs.module_path }} to dev
    needs: test-build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write    # Required for nais/deploy OIDC
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Deploy application
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ${{ inputs.module_path }}/.nais/nais-dev.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
          VARS: ${{ inputs.module_path }}/.nais/vars-dev.yaml

  deploy-prod:
    name: Deploy ${{ inputs.module_path }} to prod
    needs: [ test-build-and-push, deploy-dev ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write    # Required for nais/deploy OIDC
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Deploy application
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: ${{ inputs.module_path }}/.nais/nais-prod.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
          VARS: ${{ inputs.module_path }}/.nais/vars-prod.yaml