name: Reusable Run Tests

on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    name: Run ${{ inputs.module_path }} tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Java
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Run tests
        run: |
          GRADLE_ARGS=""
          
          if [ "${{ inputs.module_path }}" != "all" ]; then
            GRADLE_ARGS="-p ${{ inputs.module_path }}"
          fi
          
          ./gradlew check \
            $GRADLE_ARGS \
            --no-daemon \
            --no-configuration-cache
# Kommenter inn ved behov
#             --info \
#             --console=plain \
#             --warning-mode=all
