name: Reusable Run Tests

on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    name: Run ${{ inputs.module_path }} tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Run tests
        run: |
          GRADLE_ARGS=""
          
          if [ "${{ inputs.module_path }}" != "all" ]; then
            GRADLE_ARGS="-p ${{ inputs.module_path }}"
          fi
          
          ./gradlew check \
            $GRADLE_ARGS \
            --no-daemon \
            --no-configuration-cache
# Kommenter inn ved behov
#             --info \
#             --console=plain \
#             --warning-mode=all
