name: Reusable Run Tests

on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    name: Run ${{ inputs.module_path }} tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Run tests
        run: |
          GRADLE_ARGS=""
          
          if [ "${{ inputs.module_path }}" != "all" ]; then
            GRADLE_ARGS="-p ${{ inputs.module_path }}"
          fi
          
          ./gradlew check \
            $GRADLE_ARGS \
            --no-daemon \
            --no-configuration-cache
# Kommenter inn ved behov
#             --info \
#             --console=plain \
#             --warning-mode=all
