name: Reusable Deploy Unleash API Token

on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string

permissions:
  id-token: write

jobs:
  deploy-dev:
    name: Deploy ${{ inputs.module_path }} Unleash to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ${{ inputs.module_path }}/.nais/unleash-apitoken-dev.yaml
          PRINT_PAYLOAD: true

  deploy-prod:
    name: Deploy ${{ inputs.module_path }} Unleash to prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: ${{ inputs.module_path }}/.nais/unleash-apitoken-prod.yaml