name: amt-deltakelser - Run all tests
on:
  push:
    paths:
      - "gradle/libs.versions.toml"
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  run-tests:
    uses: ./.github/workflows/reusable/test.yml
    with:
      module-path: "all"