UPDATE deltakerliste
SET tiltakstype = CASE tiltakstype
    WHEN 'ARBFORB' THEN 'ARBEIDSFORBEREDENDE_TRENING'
    WHEN 'ARBRRHDAG' THEN 'ARBEIDSRETTET_REHABILITERING'
    WHEN 'AVKLARAG' THEN 'AVKLARING'
    WHEN 'DIGIOPPARB' THEN 'DIGITALT_OPPFOLGINGSTILTAK'
    WHEN 'GRUPPEAMO' THEN 'GRUPPE_ARBEIDSMARKEDSOPPLAERING'
    WHEN 'GRUFAGYRKE' THEN 'GRUPPE_FAG_OG_YRKESOPPLAERING'
    WHEN 'INDOPPFAG' THEN 'OPPFOLGING'
    WHEN 'VASV' THEN 'VARIG_TILRETTELAGT_ARBEID_SKJERMET'
    WHEN 'JOBBK' THEN 'JOBBKLUBB'
    ELSE 'UKJENT'
END;