ALTER TABLE arrangor OWNER TO CURRENT_USER;
ALTER TABLE deltaker OWNER TO CURRENT_USER;
ALTER TABLE deltakerliste OWNER TO CURRENT_USER;
ALTER TABLE feilmelding OWNER TO CURRENT_USER;
ALTER TABLE melding OWNER TO CURRENT_USER;
ALTER TABLE oppfolgingsperiode OWNER TO CURRENT_USER;
